[package]
name = "lean-category-theory-pr"
version = "0.1"
lean_version = "nightly-2018-06-21"
path = "src"

[dependencies]
mathlib = {git = "git@github.com:leanprover-community/mathlib.git", rev = "313fb7d943b5c37d2d4b33dc7c67ddc88723e84a"}
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "68b77c2e97a86f6751c5e52d6af734f765f1eb40"}
