[package]
name = "lean-category-theory-pr"
version = "0.1"
lean_version = "nightly-2018-04-06"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "72a968cc1c1a490aae50a39332abde0f321d36de"}
