[package]
name = "lean-category-theory-pr"
version = "0.1"
lean_version = "nightly-2018-04-06"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "923c22814162587efca0182f9169858b26ae3882"}
