[package]
name = "lean-category-theory-pr"
version = "0.1"
lean_version = "nightly-2018-04-20"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "69cad245e6b17c74ed9323d56858c0fd61ed2791"}
