[package]
name = "lean-category-theory-pr"
version = "0.1"
lean_version = "nightly-2018-06-21"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "668f99ed1b91a0e504d2e4944bd5e50abeec3ff0"}
